services:
  # FastAPI Backend Service
  - type: web
    name: job-platform-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: ADZUNA_APP_ID # Example, replace with your actual keys if not hardcoded
        value: "478e2d58" # Replace with your Adzuna App ID
      - key: ADZUNA_API_KEY # Example, replace with your actual keys if not hardcoded
        value: "003d6ccef719aec08d8442a7555c1060" # Replace with your Adzuna API Key

  # Next.js Frontend Service
  - type: web
    name: job-platform-frontend
    env: node
    rootDir: . # Points to the root of your repository
    buildCommand: pnpm install --frozen-lockfile && pnpm run build
    startCommand: pnpm start
    envVars:
      - key: NEXT_PUBLIC_API_URL # This will be set manually in Render dashboard after backend is deployed
        value: "" # Leave empty for now, will be populated on Render after backend deployment

  # A common practice is to use Render's internal service discovery:
  # value: http://job-platform-backend.onrender.com # Use your backend service's internal hostname for direct communication 